import * as fs from 'fs-extra';
import * as path from 'path';
import * as crypto from 'crypto';
import chalk from 'chalk';
import prompts from 'prompts';
import { EnvironmentProfile, loadProfileConfig, saveProfileConfig } from './profile';

/**
 * Profile versioning and rollback system
 * Track profile changes, create snapshots, and rollback to previous versions
 */

const VERSIONS_DIR = '.re-shell/profile-versions';
const VERSION_INDEX_FILE = '.re-shell/profile-version-index.json';
const MAX_VERSIONS_PER_PROFILE = 20;
const AUTO_SNAPSHOT_THRESHOLD = 5; // Create snapshot after N changes

export interface ProfileVersion {
  versionId: string;
  profileName: string;
  timestamp: string;
  createdBy: string;
  message?: string;
  tags: string[];
  changes: string[];
  profileHash: string;
  autoGenerated: boolean;
  compressed: boolean;
}

export interface VersionIndex {
  profiles: Record<string, string[]>; // profileName -> versionIds[]
  currentVersions: Record<string, string>; // profileName -> versionId
  lastAutoSnapshot: Record<string, number>; // profileName -> changeCount
}

export interface VersionDiff {
  added: string[];
  removed: string[];
  modified: string[];
  unchanged: string[];
}

/**
 * Create a snapshot of current profile state
 */
export async function createProfileVersion(
  profileName: string,
  options: {
    message?: string;
    tags?: string[];
    auto?: boolean;
  } = {}
): Promise<string | null> {
  const config = await loadProfileConfig();
  const profile = config.profiles[profileName];

  if (!profile) {
    console.log(chalk.red(`\n✗ Profile "${profileName}" not found\n`));
    return null;
  }

  // Ensure versions directory exists
  await fs.ensureDir(path.join(process.cwd(), VERSIONS_DIR));

  // Load version index
  const index = await loadVersionIndex();

  // Generate version ID
  const versionId = `${profileName}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;
  const profileHash = crypto.createHash('sha256').update(JSON.stringify(profile)).digest('hex');

  // Create version metadata
  const version: ProfileVersion = {
    versionId,
    profileName,
    timestamp: new Date().toISOString(),
    createdBy: process.env.USER || 'unknown',
    message: options.message || (options.auto ? 'Automatic snapshot' : 'Manual snapshot'),
    tags: options.tags || [],
    changes: [], // Will be populated if comparing with previous version
    profileHash,
    autoGenerated: options.auto || false,
    compressed: false,
  };

  // Calculate changes if there's a previous version
  if (index.currentVersions[profileName]) {
    const previousVersionId = index.currentVersions[profileName];
    const previousVersionData = await loadProfileVersion(previousVersionId);

    if (previousVersionData) {
      version.changes = calculateChanges(previousVersionData.version.profileHash, profileHash);
    }
  }

  // Save profile version
  const versionPath = path.join(process.cwd(), VERSIONS_DIR, `${versionId}.json`);
  await fs.writeFile(versionPath, JSON.stringify({ version, profile }, null, 2), 'utf8');

  // Update index
  if (!index.profiles[profileName]) {
    index.profiles[profileName] = [];
  }

  index.profiles[profileName].push(versionId);
  index.currentVersions[profileName] = versionId;

  // Clean up old versions if exceeding limit
  if (index.profiles[profileName].length > MAX_VERSIONS_PER_PROFILE) {
    const versionsToRemove = index.profiles[profileName].slice(0, -MAX_VERSIONS_PER_PROFILE);

    for (const oldVersionId of versionsToRemove) {
      await deleteProfileVersion(oldVersionId, profileName);
    }

    index.profiles[profileName] = index.profiles[profileName].slice(-MAX_VERSIONS_PER_PROFILE);
  }

  await saveVersionIndex(index);

  console.log(chalk.green(`✓ Created version ${versionId.slice(0, 12)}... for profile "${profileName}"`));

  return versionId;
}

/**
 * List all versions of a profile
 */
export async function listProfileVersions(profileName: string): Promise<void> {
  const index = await loadVersionIndex();

  if (!index.profiles[profileName] || index.profiles[profileName].length === 0) {
    console.log(chalk.yellow(`\n⚠ No versions found for profile "${profileName}"\n`));
    return;
  }

  const versionIds = index.profiles[profileName];
  const currentVersionId = index.currentVersions[profileName];

  console.log(chalk.cyan.bold(`\n📜 Version History for "${profileName}"\n`));

  for (let i = 0; i < versionIds.length; i++) {
    const versionId = versionIds[i];
    const versionData = await loadProfileVersion(versionId);

    if (!versionData) continue;

    const { version} = versionData;
    const isCurrent = versionId === currentVersionId;
    const isAuto = version.autoGenerated;

    const icon = isCurrent ? '📍' : '  ';
    const autoBadge = isAuto ? chalk.gray('[auto]') : '';
    const currentBadge = isCurrent ? chalk.green('[current]') : '';

    console.log(chalk.white(`${icon} Version ${i + 1}: ${versionId.slice(0, 12)}... ${autoBadge} ${currentBadge}`));
    console.log(chalk.gray(`    Created: ${formatDate(version.timestamp)}`));
    console.log(chalk.gray(`    By: ${version.createdBy}`));

    if (version.message) {
      console.log(chalk.gray(`    ${version.message}`));
    }

    if (version.tags.length > 0) {
      console.log(chalk.cyan(`    Tags: ${version.tags.join(', ')}`));
    }

    if (version.changes.length > 0) {
      console.log(chalk.gray(`    Changes: ${version.changes.length} modification(s)`));
    }

    console.log(chalk.gray(`    Hash: ${version.profileHash.slice(0, 16)}...`));
    console.log('');
  }
}

/**
 * Rollback profile to a specific version
 */
export async function rollbackProfile(
  profileName: string,
  versionIdOrNumber: string,
  options: {
    force?: boolean;
    createBackup?: boolean;
  } = {}
): Promise<void> {
  const index = await loadVersionIndex();

  if (!index.profiles[profileName] || index.profiles[profileName].length === 0) {
    console.log(chalk.yellow(`\n⚠ No versions found for profile "${profileName}"\n`));
    return;
  }

  // Determine version ID
  let targetVersionId: string;

  if (/^\d+$/.test(versionIdOrNumber)) {
    // Version number (1-based index)
    const versionNumber = parseInt(versionIdOrNumber);
    const versionIds = index.profiles[profileName];

    if (versionNumber < 1 || versionNumber > versionIds.length) {
      console.log(chalk.red(`\n✗ Invalid version number: ${versionNumber}\n`));
      console.log(chalk.gray(`Valid range: 1-${versionIds.length}\n`));
      return;
    }

    targetVersionId = versionIds[versionNumber - 1];
  } else {
    // Version ID (partial match supported)
    const versionIds = index.profiles[profileName];
    const match = versionIds.find(id => id.startsWith(versionIdOrNumber));

    if (!match) {
      console.log(chalk.red(`\n✗ Version ID not found: ${versionIdOrNumber}\n`));
      return;
    }

    targetVersionId = match;
  }

  // Load target version
  const versionData = await loadProfileVersion(targetVersionId);

  if (!versionData) {
    console.log(chalk.red(`\n✗ Failed to load version: ${targetVersionId}\n`));
    return;
  }

  const { version, profile } = versionData;

  console.log(chalk.cyan.bold(`\n🔄 Rolling back "${profileName}"\n`));
  console.log(chalk.gray(`Target version: ${targetVersionId.slice(0, 12)}...`));
  console.log(chalk.gray(`Created: ${formatDate(version.timestamp)}`));
  console.log(chalk.gray(`By: ${version.createdBy}`));

  if (version.message) {
    console.log(chalk.gray(`Message: ${version.message}\n`));
  }

  // Confirm rollback
  if (!options.force) {
    const { value: confirmed } = await prompts({
      type: 'confirm',
      name: 'value',
      message: 'Rollback to this version?',
      initial: false,
    });

    if (!confirmed) {
      console.log(chalk.yellow('\n✖ Rollback cancelled\n'));
      return;
    }
  }

  // Create backup of current state
  if (options.createBackup) {
    console.log(chalk.gray('Creating backup of current state...'));
    await createProfileVersion(profileName, {
      message: 'Backup before rollback',
      tags: ['backup', 'before-rollback'],
      auto: false,
    });
  }

  // Restore profile
  const config = await loadProfileConfig();
  config.profiles[profileName] = profile;
  await saveProfileConfig(config);

  // Update current version in index
  index.currentVersions[profileName] = targetVersionId;
  await saveVersionIndex(index);

  console.log(chalk.green(`\n✓ Successfully rolled back "${profileName}" to version ${targetVersionId.slice(0, 12)}...\n`));

  // Show profile info
  console.log(chalk.cyan('Restored profile:'));
  console.log(chalk.gray(`  Name: ${profile.name}`));
  console.log(chalk.gray(`  Environment: ${profile.environment}`));
  if (profile.framework) {
    console.log(chalk.gray(`  Framework: ${profile.framework}`));
  }
  if (profile.description) {
    console.log(chalk.gray(`  Description: ${profile.description}`));
  }
  console.log('');
}

/**
 * Compare two versions of a profile
 */
export async function compareProfileVersions(
  profileName: string,
  version1IdOrNumber: string,
  version2IdOrNumber?: string
): Promise<void> {
  const index = await loadVersionIndex();

  if (!index.profiles[profileName] || index.profiles[profileName].length === 0) {
    console.log(chalk.yellow(`\n⚠ No versions found for profile "${profileName}"\n`));
    return;
  }

  const versionIds = index.profiles[profileName];

  // If only one version specified, compare with current
  if (!version2IdOrNumber) {
    version2IdOrNumber = versionIds.length.toString();
  }

  // Resolve version IDs
  const resolveVersionId = (input: string): string | null => {
    if (/^\d+$/.test(input)) {
      const num = parseInt(input);
      if (num < 1 || num > versionIds.length) return null;
      return versionIds[num - 1];
    }
    return versionIds.find(id => id.startsWith(input)) || null;
  };

  const v1Id = resolveVersionId(version1IdOrNumber);
  const v2Id = resolveVersionId(version2IdOrNumber);

  if (!v1Id || !v2Id) {
    console.log(chalk.red('\n✗ Invalid version identifier(s)\n'));
    return;
  }

  // Load versions
  const v1Data = await loadProfileVersion(v1Id);
  const v2Data = await loadProfileVersion(v2Id);

  if (!v1Data || !v2Data) {
    console.log(chalk.red('\n✗ Failed to load version(s)\n'));
    return;
  }

  // Calculate diff
  const diff = calculateProfileDiff(v1Data.profile, v2Data.profile);

  console.log(chalk.cyan.bold(`\n🔍 Comparing versions of "${profileName}"\n`));
  console.log(chalk.gray(`Version 1: ${v1Id.slice(0, 12)}... (${formatDate(v1Data.version.timestamp)})`));
  console.log(chalk.gray(`Version 2: ${v2Id.slice(0, 12)}... (${formatDate(v2Data.version.timestamp)})\n`));

  if (diff.unchanged.length === 0 && diff.added.length === 0 && diff.modified.length === 0 && diff.removed.length === 0) {
    console.log(chalk.cyan('✨ Profiles are identical\n'));
    return;
  }

  if (diff.added.length > 0) {
    console.log(chalk.green.bold('Added:'));
    diff.added.forEach(item => console.log(chalk.green(`  + ${item}`)));
    console.log('');
  }

  if (diff.removed.length > 0) {
    console.log(chalk.red.bold('Removed:'));
    diff.removed.forEach(item => console.log(chalk.red(`  - ${item}`)));
    console.log('');
  }

  if (diff.modified.length > 0) {
    console.log(chalk.yellow.bold('Modified:'));
    diff.modified.forEach(item => console.log(chalk.yellow(`  ~ ${item}`)));
    console.log('');
  }

  if (diff.unchanged.length > 0) {
    console.log(chalk.gray.bold('Unchanged:'));
    diff.unchanged.forEach(item => console.log(chalk.gray(`  = ${item}`)));
    console.log('');
  }
}

/**
 * Delete old versions
 */
export async function cleanupOldVersions(
  profileName?: string,
  options: {
    keep?: number;
    before?: string; // ISO date string
    autoOnly?: boolean;
  } = {}
): Promise<void> {
  const index = await loadVersionIndex();
  let deleted = 0;

  const processProfile = async (name: string) => {
    if (!index.profiles[name] || index.profiles[name].length === 0) {
      return;
    }

    const versions = index.profiles[name];
    const toDelete: string[] = [];

    for (const versionId of versions) {
      const versionData = await loadProfileVersion(versionId);

      if (!versionData) continue;

      const { version } = versionData;

      // Check conditions
      if (options.autoOnly && !version.autoGenerated) {
        continue;
      }

      if (options.before && new Date(version.timestamp) >= new Date(options.before)) {
        continue;
      }

      // Keep N most recent versions
      if (options.keep) {
        // Sort versions by timestamp (descending)
        const versionTimestamps: Record<string, number> = {};

        for (const vid of versions) {
          const vData = await loadProfileVersion(vid);
          if (vData) {
            versionTimestamps[vid] = new Date(vData.version.timestamp).getTime();
          }
        }

        const sortedVersions = versions.sort((a, b) => {
          const aTime = versionTimestamps[a] || 0;
          const bTime = versionTimestamps[b] || 0;
          return bTime - aTime;
        });

        const keepIndex = sortedVersions.indexOf(versionId);
        if (keepIndex < options.keep) {
          continue;
        }
      }

      toDelete.push(versionId);
    }

    // Delete versions
    for (const versionId of toDelete) {
      await deleteProfileVersion(versionId, name);
      deleted++;
    }

    // Update index
    index.profiles[name] = versions.filter(v => !toDelete.includes(v));
  };

  if (profileName) {
    await processProfile(profileName);
  } else {
    for (const name of Object.keys(index.profiles)) {
      await processProfile(name);
    }
  }

  await saveVersionIndex(index);

  if (deleted > 0) {
    console.log(chalk.green(`\n✓ Deleted ${deleted} old version(s)\n`));
  } else {
    console.log(chalk.gray('\n✓ No versions to delete\n'));
  }
}

/**
 * Auto-snapshot before major changes
 */
export async function autoSnapshotIfNeeded(profileName: string): Promise<void> {
  const index = await loadVersionIndex();

  if (!index.lastAutoSnapshot) {
    index.lastAutoSnapshot = {};
  }

  index.lastAutoSnapshot[profileName] = (index.lastAutoSnapshot[profileName] || 0) + 1;

  if (index.lastAutoSnapshot[profileName] >= AUTO_SNAPSHOT_THRESHOLD) {
    await createProfileVersion(profileName, {
      message: `Automatic snapshot after ${AUTO_SNAPSHOT_THRESHOLD} changes`,
      tags: ['auto', 'snapshot'],
      auto: true,
    });

    index.lastAutoSnapshot[profileName] = 0;
    await saveVersionIndex(index);
  }
}

/**
 * Helper functions
 */

async function loadVersionIndex(): Promise<VersionIndex> {
  const indexPath = path.join(process.cwd(), VERSION_INDEX_FILE);

  if (!(await fs.pathExists(indexPath))) {
    const emptyIndex: VersionIndex = {
      profiles: {},
      currentVersions: {},
      lastAutoSnapshot: {},
    };
    await fs.writeFile(indexPath, JSON.stringify(emptyIndex, null, 2), 'utf8');
    return emptyIndex;
  }

  const content = await fs.readFile(indexPath, 'utf8');
  return JSON.parse(content);
}

async function saveVersionIndex(index: VersionIndex): Promise<void> {
  const indexPath = path.join(process.cwd(), VERSION_INDEX_FILE);
  await fs.writeFile(indexPath, JSON.stringify(index, null, 2), 'utf8');
}

async function loadProfileVersion(versionId: string): Promise<{ version: ProfileVersion; profile: EnvironmentProfile } | null> {
  const versionPath = path.join(process.cwd(), VERSIONS_DIR, `${versionId}.json`);

  if (!(await fs.pathExists(versionPath))) {
    return null;
  }

  const content = await fs.readFile(versionPath, 'utf8');
  return JSON.parse(content);
}

async function deleteProfileVersion(versionId: string, profileName: string): Promise<void> {
  const versionPath = path.join(process.cwd(), VERSIONS_DIR, `${versionId}.json`);

  if (await fs.pathExists(versionPath)) {
    await fs.remove(versionPath);
  }
}

function calculateChanges(oldHash: string, newHash: string): string[] {
  if (oldHash === newHash) {
    return ['No changes'];
  }

  return ['Configuration modified'];
}

function calculateProfileDiff(profile1: EnvironmentProfile, profile2: EnvironmentProfile): VersionDiff {
  const diff: VersionDiff = {
    added: [],
    removed: [],
    modified: [],
    unchanged: [],
  };

  // Compare basic properties
  if (profile1.name !== profile2.name) diff.modified.push('name');
  if (profile1.description !== profile2.description) {
    if (profile1.description && !profile2.description) diff.removed.push('description');
    else if (!profile1.description && profile2.description) diff.added.push('description');
    else diff.modified.push('description');
  }
  if (profile1.framework !== profile2.framework) {
    if (profile1.framework && !profile2.framework) diff.removed.push('framework');
    else if (!profile1.framework && profile2.framework) diff.added.push('framework');
    else diff.modified.push('framework');
  }
  if (profile1.environment !== profile2.environment) diff.modified.push('environment');

  // Compare config sections
  const p1Config = profile1.config;
  const p2Config = profile2.config;

  if (p1Config.build && !p2Config.build) diff.removed.push('build config');
  else if (!p1Config.build && p2Config.build) diff.added.push('build config');
  else if (p1Config.build && p2Config.build) {
    if (JSON.stringify(p1Config.build) !== JSON.stringify(p2Config.build)) {
      diff.modified.push('build config');
    }
  }

  if (p1Config.dev && !p2Config.dev) diff.removed.push('dev config');
  else if (!p1Config.dev && p2Config.dev) diff.added.push('dev config');
  else if (p1Config.dev && p2Config.dev) {
    if (JSON.stringify(p1Config.dev) !== JSON.stringify(p2Config.dev)) {
      diff.modified.push('dev config');
    }
  }

  if (p1Config.test && !p2Config.test) diff.removed.push('test config');
  else if (!p1Config.test && p2Config.test) diff.added.push('test config');
  else if (p1Config.test && p2Config.test) {
    if (JSON.stringify(p1Config.test) !== JSON.stringify(p2Config.test)) {
      diff.modified.push('test config');
    }
  }

  // Environment variables
  const p1EnvKeys = new Set(Object.keys(p1Config.env || {}));
  const p2EnvKeys = new Set(Object.keys(p2Config.env || {}));

  p1EnvKeys.forEach(key => {
    if (!p2EnvKeys.has(key)) diff.removed.push(`env var: ${key}`);
    else if (p1Config.env![key] !== p2Config.env![key]) diff.modified.push(`env var: ${key}`);
  });

  p2EnvKeys.forEach(key => {
    if (!p1EnvKeys.has(key)) diff.added.push(`env var: ${key}`);
  });

  // Scripts
  const p1ScriptKeys = new Set(Object.keys(p1Config.scripts || {}));
  const p2ScriptKeys = new Set(Object.keys(p2Config.scripts || {}));

  p1ScriptKeys.forEach(key => {
    if (!p2ScriptKeys.has(key)) diff.removed.push(`script: ${key}`);
    else if (p1Config.scripts![key] !== p2Config.scripts![key]) diff.modified.push(`script: ${key}`);
  });

  p2ScriptKeys.forEach(key => {
    if (!p1ScriptKeys.has(key)) diff.added.push(`script: ${key}`);
  });

  // Services
  const p1Services = new Set(p1Config.services || []);
  const p2Services = new Set(p2Config.services || []);

  p1Services.forEach(svc => {
    if (!p2Services.has(svc)) diff.removed.push(`service: ${svc}`);
  });

  p2Services.forEach(svc => {
    if (!p1Services.has(svc)) diff.added.push(`service: ${svc}`);
  });

  // Extends
  const p1Extends = new Set(profile1.extends || []);
  const p2Extends = new Set(profile2.extends || []);

  p1Extends.forEach(ext => {
    if (!p2Extends.has(ext)) diff.removed.push(`extends: ${ext}`);
  });

  p2Extends.forEach(ext => {
    if (!p1Extends.has(ext)) diff.added.push(`extends: ${ext}`);
  });

  return diff;
}

function formatDate(isoString: string): string {
  const date = new Date(isoString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;

  return date.toLocaleDateString();
}
