/**
 * Static role + permission fixtures for the `security rbac` command.
 * Extracted verbatim from rbac-config.ts to keep both files under the
 * 800-line limit. These are example/seed records embedded in the generated
 * scaffold output.
 */
export const roleList: any[] = [
        {
          id: 'role-super-admin',
          name: 'Super Administrator',
          description: 'Full system access with all permissions',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: false,
          priority: 1,
          inheritsFrom: undefined,
          permissions: ['perm-admin-all', 'perm-users-manage', 'perm-roles-manage', 'perm-policies-manage'],
          scopedPermissions: [],
          conditions: [],
          metadata: {
            category: 'administration',
            riskLevel: 'critical' as const,
            complianceReferences: ['SOC-2', 'ISO-27001'],
            approvalRequired: true,
            approvers: ['ceo', 'ciso'],
            reviewInterval: 90,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            version: '1.0.0',
            changeHistory: [
              { timestamp: new Date('2024-01-01'), user: 'system', action: 'created' as const, reason: 'Initial system role creation' },
            ],
            documentation: 'Super administrators have complete access to all system resources and can manage all other users, roles, and permissions.',
            rationale: 'Required for emergency system administration and initial setup.',
          },
          tags: ['admin', 'super', 'critical'],
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'role-admin',
          name: 'Administrator',
          description: 'Administrative access for managing users and resources',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: true,
          priority: 10,
          inheritsFrom: undefined,
          permissions: ['perm-users-read', 'perm-users-write', 'perm-resources-manage'],
          scopedPermissions: [],
          conditions: [],
          metadata: {
            category: 'administration',
            riskLevel: 'high' as const,
            complianceReferences: ['SOC-2'],
            approvalRequired: false,
            approvers: ['ciso'],
            reviewInterval: 90,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            version: '1.0.0',
            changeHistory: [
              { timestamp: new Date('2024-01-01'), user: 'system', action: 'created' as const, reason: 'Initial role creation' },
            ],
            documentation: 'Administrators can manage users and resources but cannot modify system configuration or roles.',
            rationale: 'Day-to-day administrative operations without full system access.',
          },
          tags: ['admin', 'operations'],
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'role-operator',
          name: 'Operator',
          description: 'Read and execute access for operational tasks',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: true,
          priority: 50,
          inheritsFrom: undefined,
          permissions: ['perm-resources-read', 'perm-services-execute'],
          scopedPermissions: [
            {
              permissionId: 'perm-resources-read',
              scope: { type: 'organization' as const, value: 'production' },
              resourceFilters: [{ field: 'resource.type', operator: 'equals' as const, value: 'service' }],
              conditions: [],
              effect: 'allow' as const,
            },
          ],
          conditions: [],
          metadata: {
            category: 'operations',
            riskLevel: 'medium' as const,
            complianceReferences: [],
            approvalRequired: false,
            approvers: [],
            reviewInterval: 180,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
            version: '1.0.0',
            changeHistory: [
              { timestamp: new Date('2024-01-15'), user: 'hr-director', action: 'created' as const, reason: 'Operations team role' },
            ],
            documentation: 'Operators can view resources and execute services but cannot modify configurations.',
            rationale: 'Operational visibility and service execution without modification rights.',
          },
          tags: ['operations', 'read-only'],
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date(),
        },
        {
          id: 'role-auditor',
          name: 'Security Auditor',
          description: 'Read-only access for security auditing and compliance',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: false,
          priority: 20,
          inheritsFrom: undefined,
          permissions: ['perm-audit-read', 'perm-logs-read', 'perm-policies-read'],
          scopedPermissions: [],
          conditions: [],
          metadata: {
            category: 'compliance',
            riskLevel: 'low' as const,
            complianceReferences: ['SOC-2', 'ISO-27001', 'PCI-DSS'],
            approvalRequired: false,
            approvers: [],
            reviewInterval: 90,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
            version: '1.0.0',
            changeHistory: [
              { timestamp: new Date('2024-01-01'), user: 'system', action: 'created' as const, reason: 'Compliance requirement' },
            ],
            documentation: 'Auditors have read-only access to logs, policies, and audit trails for compliance reporting.',
            rationale: 'Required for regulatory compliance and security audits.',
          },
          tags: ['audit', 'compliance', 'read-only'],
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
        {
          id: 'role-developer',
          name: 'Developer',
          description: 'Development access with resource creation and modification',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: true,
          priority: 75,
          inheritsFrom: 'role-operator' as const,
          permissions: ['perm-resources-create', 'perm-resources-update', 'perm-services-deploy'],
          scopedPermissions: [
            {
              permissionId: 'perm-resources-create',
              scope: { type: 'project' as const, value: 'development' },
              resourceFilters: [{ field: 'environment', operator: 'equals' as const, value: 'dev' }],
              conditions: [],
              effect: 'allow' as const,
            },
          ],
          conditions: [],
          metadata: {
            category: 'development',
            riskLevel: 'medium' as const,
            complianceReferences: [],
            approvalRequired: false,
            approvers: [],
            reviewInterval: 180,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
            version: '1.2.0',
            changeHistory: [
              { timestamp: new Date('2024-02-01'), user: 'engineering-manager', action: 'created' as const, reason: 'Development team access' },
              { timestamp: new Date('2024-06-01'), user: 'tech-lead', action: 'permissions-changed' as const, reason: 'Added deployment permissions' },
            ],
            documentation: 'Developers can create and update resources in development environments and deploy services.',
            rationale: 'Enable development workflows while protecting production environments.',
          },
          tags: ['development', 'engineering'],
          createdAt: new Date('2024-02-01'),
          updatedAt: new Date('2024-06-01'),
        },
        {
          id: 'role-viewer',
          name: 'Viewer',
          description: 'Read-only access for viewing resources and dashboards',
          status: 'active' as const,
          isSystemRole: true,
          isCustomizable: true,
          priority: 100,
          inheritsFrom: undefined,
          permissions: ['perm-dashboard-read', 'perm-resources-read'],
          scopedPermissions: [],
          conditions: [],
          metadata: {
            category: 'general',
            riskLevel: 'low' as const,
            complianceReferences: [],
            approvalRequired: false,
            approvers: [],
            reviewInterval: 365,
            lastReviewed: new Date(),
            nextReviewDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
            version: '1.0.0',
            changeHistory: [
              { timestamp: new Date('2024-01-01'), user: 'system', action: 'created' as const, reason: 'Basic read-only role' },
            ],
            documentation: 'Viewers have read-only access to dashboards and resources for monitoring purposes.',
            rationale: 'Provide visibility without modification capabilities for stakeholders.',
          },
          tags: ['read-only', 'monitoring'],
          createdAt: new Date('2024-01-01'),
          updatedAt: new Date(),
        },
];

export const permissionList: any[] = [
        {
          id: 'perm-admin-all',
          name: 'All Administrative Access',
          description: 'Full administrative access to all system resources',
          resource: 'custom' as const,
          actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const, 'admin' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [
            { type: 'mfa' as const, config: { required: true }, enforce: true },
            { type: 'ip-range' as const, config: { allowedRanges: ['10.0.0.0/8'] }, enforce: true },
          ],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'restricted' as const,
            complianceRequirements: ['SOC-2', 'ISO-27001', 'PCI-DSS'],
            riskScore: 100,
            requiresApproval: true,
            approvers: ['ceo', 'ciso', 'board'],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-users-manage',
          name: 'User Management',
          description: 'Create, read, update, and delete users',
          resource: 'users' as const,
          actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [
            { type: 'mfa' as const, config: { required: true }, enforce: true },
          ],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'confidential' as const,
            complianceRequirements: ['SOC-2', 'GDPR'],
            riskScore: 85,
            requiresApproval: false,
            approvers: ['ciso'],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-roles-manage',
          name: 'Role Management',
          description: 'Create, read, update, and delete roles',
          resource: 'roles' as const,
          actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [
            { type: 'mfa' as const, config: { required: true }, enforce: true },
          ],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'confidential' as const,
            complianceRequirements: ['SOC-2', 'ISO-27001'],
            riskScore: 90,
            requiresApproval: true,
            approvers: ['ciso', 'cto'],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-policies-manage',
          name: 'Policy Management',
          description: 'Create, read, update, and delete access policies',
          resource: 'policies' as const,
          actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [
            { type: 'mfa' as const, config: { required: true }, enforce: true },
          ],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'restricted' as const,
            complianceRequirements: ['SOC-2', 'ISO-27001', 'PCI-DSS'],
            riskScore: 95,
            requiresApproval: true,
            approvers: ['ciso', 'compliance-officer'],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-users-read',
          name: 'Read Users',
          description: 'Read-only access to user information',
          resource: 'users' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'confidential' as const,
            complianceRequirements: ['GDPR'],
            riskScore: 60,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-users-write',
          name: 'Write Users',
          description: 'Create and update users',
          resource: 'users' as const,
          actions: ['create' as const, 'update' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'confidential' as const,
            complianceRequirements: ['GDPR'],
            riskScore: 70,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-resources-manage',
          name: 'Manage Resources',
          description: 'Full access to manage system resources',
          resource: 'resources' as const,
          actions: ['create' as const, 'read' as const, 'update' as const, 'delete' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'operations',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 65,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-resources-read',
          name: 'Read Resources',
          description: 'Read-only access to resources',
          resource: 'resources' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'operations',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 30,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-services-execute',
          name: 'Execute Services',
          description: 'Execute and run services',
          resource: 'services' as const,
          actions: ['execute' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'operations',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 50,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-audit-read',
          name: 'Read Audit Logs',
          description: 'Read-only access to audit logs',
          resource: 'audit-logs' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'compliance',
            sensitivity: 'confidential' as const,
            complianceRequirements: ['SOC-2', 'ISO-27001', 'PCI-DSS'],
            riskScore: 40,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-logs-read',
          name: 'Read System Logs',
          description: 'Read-only access to system logs',
          resource: 'audit-logs' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'operations',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 35,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-policies-read',
          name: 'Read Policies',
          description: 'Read-only access to access policies',
          resource: 'policies' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'administration',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 30,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-resources-create',
          name: 'Create Resources',
          description: 'Create new resources',
          resource: 'resources' as const,
          actions: ['create' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'development',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 55,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-resources-update',
          name: 'Update Resources',
          description: 'Update existing resources',
          resource: 'resources' as const,
          actions: ['update' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'development',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 55,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-services-deploy',
          name: 'Deploy Services',
          description: 'Deploy services to environments',
          resource: 'services' as const,
          actions: ['create' as const, 'update' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [
            { type: 'time-window' as const, config: { allowedHours: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] }, enforce: true },
          ],
          status: 'granted' as const,
          metadata: {
            category: 'development',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 60,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
        {
          id: 'perm-dashboard-read',
          name: 'Read Dashboards',
          description: 'Read-only access to monitoring dashboards',
          resource: 'resources' as const,
          actions: ['read' as const],
          effect: 'allow' as const,
          isSystemPermission: true,
          constraints: [],
          status: 'granted' as const,
          metadata: {
            category: 'monitoring',
            sensitivity: 'internal' as const,
            complianceRequirements: [],
            riskScore: 20,
            requiresApproval: false,
            approvers: [],
          },
          createdAt: new Date('2024-01-01'),
        },
];
