/**
 * Static vendor + assessment fixtures for the `security vendor` command.
 * Extracted verbatim from vendor-config.ts to keep both files under the
 * 800-line limit. These are example/seed records embedded in the generated
 * scaffold output.
 */
export const vendorList: any[] = [
        {
          id: 'vendor-001',
          name: 'CloudInfrastructure Provider',
          description: 'Primary cloud infrastructure provider hosting critical workloads',
          website: 'https://example-cloud.com',
          category: 'cloud-provider' as const,
          tier: 'tier-1' as const,
          status: 'active' as const,
          riskRating: 'low' as const,
          overallScore: 85,
          lastAssessed: new Date('2024-12-01'),
          nextAssessment: new Date('2025-03-01'),
          onboardingDate: new Date('2020-01-15'),
          terminationDate: undefined,
          owner: 'infrastructure-director',
          technicalContact: 'tech-lead@example-cloud.com',
          businessContact: 'account-manager@example-cloud.com',
          escalationContact: 'escalation@example-cloud.com',
          services: ['compute', 'storage', 'database', 'networking', 'monitoring'],
          dataAccess: [
            {
              id: 'data-001',
              dataType: 'Customer Data',
              category: 'personal' as const,
              accessLevel: 'processed' as const,
              purpose: 'Service delivery and support',
              storageLocation: 'us-east-1',
              retentionPeriod: '3-years',
              encryptionRequired: true,
              encryptionVerified: true,
              dataResidency: ['US', 'EU'],
              subProcessors: [],
            },
          ],
          certifications: [
            {
              id: 'cert-001',
              name: 'SOC 2 Type II',
              framework: 'soc-2' as const,
              status: 'valid' as const,
              issueDate: new Date('2024-01-15'),
              expiryDate: new Date('2025-01-15'),
              certificateNumber: 'SOC2-2024-001',
              issuer: 'Independent Auditor',
              scope: 'Security, Availability, Confidentiality',
              verified: true,
              verifiedDate: new Date('2024-01-20'),
              evidenceUrl: 'https://example-cloud.com/soc2',
            },
            {
              id: 'cert-002',
              name: 'ISO 27001',
              framework: 'iso-27001' as const,
              status: 'valid' as const,
              issueDate: new Date('2023-06-01'),
              expiryDate: new Date('2026-06-01'),
              certificateNumber: 'ISO-27001-2023',
              issuer: 'BSI',
              scope: 'Information Security Management',
              verified: true,
              verifiedDate: new Date('2024-01-20'),
            },
          ],
          contracts: ['contract-001'],
          assessments: ['assessment-001'],
          findings: ['finding-001'],
          incidents: [],
          tags: ['critical', 'cloud', 'infrastructure'],
          regions: ['us-east-1', 'us-west-2', 'eu-west-1'],
          sla: {
            availability: 99.99,
            responseTime: 200,
            uptimeGuarantee: 99.9,
            resolutionTime: {
              critical: 4,
              high: 8,
              medium: 24,
              low: 48,
            },
            penaltyClauses: true,
            creditPercentage: 10,
            reporting: true,
            reportingFrequency: 'monthly',
          },
          spending: {
            annual: 1200000,
            currency: 'USD',
            budgetCode: 'INFRA-2024',
          },
          riskFactors: [
            {
              category: 'geopolitical' as const,
              description: 'Data center concentration risk in specific regions',
              severity: 'low' as const,
              mitigation: 'Multi-region deployment strategy',
              lastReviewed: new Date('2024-12-01'),
            },
          ],
          dependencies: [],
          dependents: ['vendor-002', 'vendor-003'],
          metadata: {
            created: new Date('2020-01-15'),
            createdBy: 'procurement-team',
            lastModified: new Date('2024-12-01'),
            modifiedBy: 'infrastructure-director',
            source: 'vendor-registration',
            externalReferences: ['D&B-123456'],
            notes: 'Strategic partner, mission-critical services',
            customFields: {},
          },
        },
        {
          id: 'vendor-002',
          name: 'Payment Gateway Service',
          description: 'Payment processing and transaction management',
          website: 'https://example-payments.com',
          category: 'software' as const,
          tier: 'tier-1' as const,
          status: 'active' as const,
          riskRating: 'medium' as const,
          overallScore: 72,
          lastAssessed: new Date('2024-11-15'),
          nextAssessment: new Date('2025-02-15'),
          onboardingDate: new Date('2021-03-01'),
          terminationDate: undefined,
          owner: 'finance-director',
          technicalContact: 'integration@example-payments.com',
          businessContact: 'account-manager@example-payments.com',
          escalationContact: 'support@example-payments.com',
          services: ['payment-processing', 'fraud-detection', 'reconciliation'],
          dataAccess: [
            {
              id: 'data-002',
              dataType: 'Financial Data',
              category: 'financial' as const,
              accessLevel: 'limited' as const,
              purpose: 'Payment processing',
              storageLocation: 'pci-dss-compliant',
              retentionPeriod: '7-years',
              encryptionRequired: true,
              encryptionVerified: true,
              dataResidency: ['US'],
              subProcessors: [],
            },
          ],
          certifications: [
            {
              id: 'cert-003',
              name: 'PCI DSS Level 1',
              framework: 'pci-dss' as const,
              status: 'valid' as const,
              issueDate: new Date('2024-01-01'),
              expiryDate: new Date('2025-01-01'),
              certificateNumber: 'PCI-DSS-L1-2024',
              issuer: 'Qualified Security Assessor',
              scope: 'Payment Card Data Processing',
              verified: true,
              verifiedDate: new Date('2024-02-01'),
            },
          ],
          contracts: ['contract-002'],
          assessments: ['assessment-002'],
          findings: ['finding-002', 'finding-003'],
          incidents: ['incident-001'],
          tags: ['critical', 'payments', 'pci-dss'],
          regions: ['US', 'CA', 'EU'],
          sla: {
            availability: 99.95,
            responseTime: 500,
            uptimeGuarantee: 99.9,
            resolutionTime: {
              critical: 1,
              high: 4,
              medium: 12,
              low: 24,
            },
            penaltyClauses: true,
            creditPercentage: 25,
            reporting: true,
            reportingFrequency: 'weekly',
          },
          spending: {
            annual: 500000,
            currency: 'USD',
            budgetCode: 'FINANCE-2024',
          },
          riskFactors: [
            {
              category: 'operational' as const,
              description: 'Single point of failure for payment processing',
              severity: 'medium' as const,
              mitigation: 'Implement backup payment provider',
              lastReviewed: new Date('2024-11-15'),
            },
          ],
          dependencies: ['vendor-001'],
          dependents: [],
          metadata: {
            created: new Date('2021-03-01'),
            createdBy: 'procurement-team',
            lastModified: new Date('2024-11-15'),
            modifiedBy: 'finance-director',
            source: 'vendor-registration',
            externalReferences: ['D&B-789012'],
            notes: 'Critical payment infrastructure, fallback provider required',
            customFields: {},
          },
        },
        {
          id: 'vendor-003',
          name: 'Analytics Platform',
          description: 'Data analytics and business intelligence platform',
          website: 'https://example-analytics.com',
          category: 'software' as const,
          tier: 'tier-2' as const,
          status: 'active' as const,
          riskRating: 'low' as const,
          overallScore: 78,
          lastAssessed: new Date('2024-10-01'),
          nextAssessment: new Date('2025-01-01'),
          onboardingDate: new Date('2022-06-15'),
          terminationDate: undefined,
          owner: 'data-director',
          technicalContact: 'support@example-analytics.com',
          businessContact: 'sales@example-analytics.com',
          escalationContact: undefined,
          services: ['data-visualization', 'reporting', 'ml-models'],
          dataAccess: [
            {
              id: 'data-003',
              dataType: 'Operational Metrics',
              category: 'confidential' as const,
              accessLevel: 'read-only' as const,
              purpose: 'Business analytics and reporting',
              storageLocation: 'analytics-platform',
              retentionPeriod: '2-years',
              encryptionRequired: true,
              encryptionVerified: true,
              dataResidency: ['US'],
              subProcessors: [],
            },
          ],
          certifications: [],
          contracts: ['contract-003'],
          assessments: ['assessment-003'],
          findings: [],
          incidents: [],
          tags: ['analytics', 'bi', 'reporting'],
          regions: ['US'],
          sla: {
            availability: 99.5,
            responseTime: 1000,
            uptimeGuarantee: 99.0,
            resolutionTime: {
              critical: 8,
              high: 24,
              medium: 48,
              low: 72,
            },
            penaltyClauses: false,
            creditPercentage: 0,
            reporting: false,
            reportingFrequency: 'monthly',
          },
          spending: {
            annual: 200000,
            currency: 'USD',
            budgetCode: 'DATA-2024',
          },
          riskFactors: [],
          dependencies: ['vendor-001'],
          dependents: [],
          metadata: {
            created: new Date('2022-06-15'),
            createdBy: 'data-team',
            lastModified: new Date('2024-10-01'),
            modifiedBy: 'data-director',
            source: 'vendor-registration',
            externalReferences: [],
            notes: 'Non-critical analytics platform',
            customFields: {},
          },
        },
];

export const assessmentList: any[] = [
        {
          id: 'assessment-001',
          vendorId: 'vendor-001',
          vendorName: 'CloudInfrastructure Provider',
          assessmentDate: new Date('2024-12-01'),
          assessor: 'security-team',
          reviewers: ['ciso', 'infrastructure-director'],
          status: 'completed' as const,
          type: 'periodic' as const,
          scope: {
            services: ['compute', 'storage', 'database'],
            regions: ['us-east-1', 'eu-west-1'],
            dataTypes: ['Customer Data', 'Application Data'],
            processes: ['data-storage', 'data-processing', 'backup'],
            excludeScope: ['development-environments'],
          },
          securityPosture: {
            overallScore: 88,
            domains: [
              {
                id: 'domain-001',
                name: 'Access Control',
                category: 'access-control' as const,
                score: 92,
                weight: 20,
                findings: [],
                maturityLevel: 'managed' as const,
              },
              {
                id: 'domain-002',
                name: 'Encryption',
                category: 'encryption' as const,
                score: 95,
                weight: 20,
                findings: [],
                maturityLevel: 'optimized' as const,
              },
              {
                id: 'domain-003',
                name: 'Incident Response',
                category: 'incident-response' as const,
                score: 78,
                weight: 15,
                findings: ['finding-001'],
                maturityLevel: 'defined' as const,
              },
            ],
            controls: [
              {
                id: 'ctrl-001',
                name: 'MFA for Admin Access',
                description: 'Multi-factor authentication required for all administrative access',
                type: 'preventive' as const,
                status: 'implemented' as const,
                effectiveness: 'high' as const,
                testingMethod: 'Automated verification',
                lastTested: new Date('2024-11-15'),
                testResult: 'pass' as const,
                evidence: ['test-result-001'],
              },
            ],
            vulnerabilities: [],
            testingPerformed: {
              penetrationTest: true,
              testDate: new Date('2024-10-15'),
              testProvider: 'External Security Firm',
              vulnerabilityScan: true,
              scanDate: new Date('2024-11-01'),
              codeReview: false,
              complianceAudit: true,
              auditDate: new Date('2024-09-01'),
            },
          },
          complianceAssessment: {
            overallScore: 90,
            frameworks: [
              {
                framework: 'SOC 2',
                status: 'compliant' as const,
                score: 95,
                requirements: [
                  {
                    requirementId: 'CC6.1',
                    description: 'Logical and physical access controls',
                    status: 'compliant' as const,
                    gap: undefined,
                    evidence: ['policy-001', 'audit-001'],
                  },
                ],
                lastReviewed: new Date('2024-11-01'),
                nextReview: new Date('2025-02-01'),
              },
              {
                framework: 'ISO 27001',
                status: 'compliant' as const,
                score: 88,
                requirements: [
                  {
                    requirementId: 'A.9.2.1',
                    description: 'User access management',
                    status: 'compliant' as const,
                    gap: undefined,
                    evidence: ['access-policy-001'],
                  },
                ],
                lastReviewed: new Date('2024-10-01'),
                nextReview: new Date('2025-01-01'),
              },
            ],
            gaps: [],
            evidenceRequests: [],
          },
          operationalMaturity: {
            overallScore: 82,
            peopleScore: 80,
            processScore: 85,
            technologyScore: 82,
            metrics: [
              {
                name: 'Response Time',
                value: 85,
                target: 90,
                status: 'on-track' as const,
                trend: 'improving' as const,
              },
            ],
          },
          financialHealth: {
            overallScore: 85,
            revenue: '$10B+',
            profitability: 'Profitable',
            debtToEquity: 'Low',
            yearsInBusiness: 15,
            employeeCount: 100000,
            insuranceCoverage: true,
            insuranceAmount: 50000000,
            dependencies: [],
          },
          riskScore: 15,
          riskRating: 'low' as const,
          findings: ['finding-001'],
          recommendations: [
            'Improve incident response documentation',
            'Consider more frequent penetration testing',
          ],
          approvedBy: 'ciso',
          approvedAt: new Date('2024-12-05'),
          expiryDate: new Date('2025-03-01'),
          nextAssessment: new Date('2025-03-01'),
        },
        {
          id: 'assessment-002',
          vendorId: 'vendor-002',
          vendorName: 'Payment Gateway Service',
          assessmentDate: new Date('2024-11-15'),
          assessor: 'security-team',
          reviewers: ['ciso', 'finance-director'],
          status: 'completed' as const,
          type: 'event-driven' as const,
          scope: {
            services: ['payment-processing'],
            regions: ['US'],
            dataTypes: ['Financial Data'],
            processes: ['payment-authentication', 'settlement'],
            excludeScope: [],
          },
          securityPosture: {
            overallScore: 72,
            domains: [
              {
                id: 'domain-004',
                name: 'Data Protection',
                category: 'data-protection' as const,
                score: 90,
                weight: 25,
                findings: [],
                maturityLevel: 'managed' as const,
              },
              {
                id: 'domain-005',
                name: 'Network Security',
                category: 'network-security' as const,
                score: 65,
                weight: 20,
                findings: ['finding-002'],
                maturityLevel: 'defined' as const,
              },
            ],
            controls: [],
            vulnerabilities: [],
            testingPerformed: {
              penetrationTest: true,
              testDate: new Date('2024-08-01'),
              testProvider: 'PCI QSA',
              vulnerabilityScan: true,
              scanDate: new Date('2024-10-15'),
              codeReview: false,
              complianceAudit: true,
              auditDate: new Date('2024-09-15'),
            },
          },
          complianceAssessment: {
            overallScore: 85,
            frameworks: [
              {
                framework: 'PCI DSS',
                status: 'compliant' as const,
                score: 90,
                requirements: [],
                lastReviewed: new Date('2024-09-15'),
                nextReview: new Date('2025-03-15'),
              },
            ],
            gaps: [],
            evidenceRequests: [],
          },
          operationalMaturity: {
            overallScore: 75,
            peopleScore: 75,
            processScore: 78,
            technologyScore: 72,
            metrics: [],
          },
          financialHealth: {
            overallScore: 70,
            revenue: '$1-5B',
            profitability: 'Profitable',
            debtToEquity: 'Medium',
            yearsInBusiness: 8,
            employeeCount: 2000,
            insuranceCoverage: true,
            insuranceAmount: 10000000,
            dependencies: [],
          },
          riskScore: 28,
          riskRating: 'medium' as const,
          findings: ['finding-002', 'finding-003'],
          recommendations: [
            'Implement backup payment gateway for redundancy',
            'Improve network security controls',
          ],
          approvedBy: 'ciso',
          approvedAt: new Date('2024-11-20'),
          expiryDate: new Date('2025-02-15'),
          nextAssessment: new Date('2025-02-15'),
        },
        {
          id: 'assessment-003',
          vendorId: 'vendor-003',
          vendorName: 'Analytics Platform',
          assessmentDate: new Date('2024-10-01'),
          assessor: 'data-team',
          reviewers: ['data-director'],
          status: 'completed' as const,
          type: 'periodic' as const,
          scope: {
            services: ['data-visualization', 'reporting'],
            regions: ['US'],
            dataTypes: ['Operational Metrics'],
            processes: ['analytics', 'reporting'],
            excludeScope: [],
          },
          securityPosture: {
            overallScore: 75,
            domains: [],
            controls: [],
            vulnerabilities: [],
            testingPerformed: {
              penetrationTest: false,
              vulnerabilityScan: true,
              scanDate: new Date('2024-09-15'),
              codeReview: false,
              complianceAudit: false,
            },
          },
          complianceAssessment: {
            overallScore: 80,
            frameworks: [],
            gaps: [],
            evidenceRequests: [],
          },
          operationalMaturity: {
            overallScore: 78,
            peopleScore: 75,
            processScore: 80,
            technologyScore: 80,
            metrics: [],
          },
          financialHealth: {
            overallScore: 75,
            revenue: '$100M-1B',
            profitability: 'Profitable',
            debtToEquity: 'Low',
            yearsInBusiness: 5,
            employeeCount: 500,
            insuranceCoverage: true,
            insuranceAmount: 5000000,
            dependencies: [],
          },
          riskScore: 22,
          riskRating: 'low' as const,
          findings: [],
          recommendations: [],
          expiryDate: new Date('2025-01-01'),
          nextAssessment: new Date('2025-01-01'),
        },
];
